---

task_bridge:
  debug: false
  delete_completed: false
  personal_tags: 
    - Personal
  work_tags: []
  log_file: service_sync.log
  primary_service: Omnifocus 
  update_ids_for_existing_items: false
  sync:
    # use "0" to disable
    max_age: "0"
    services: 
      - Reclaim
      - Github
      - Instapaper
      - Asana
      - TaskBridgeWeb 
    tags: 
      - TaskBridge 

asana:
  personal_access_token: ~
  projects: TaskBridge

github:
  access_code: github_access_code.txt
  client_id: ~
  client_secret: ~
  repositories: viamin/task_bridge

google:
  client: 
    id: ~
    secret: ~
    secrets_file: ./google_api_client_credentials.json
  credential_store: ./credentials.yaml
  tasks_list: My Tasks

instapaper:
  oauth:
    consumer_id: ___nil___
    consumer_secret: ___nil___
  project: ___nil___
  username: ___nil___ 
  password: ___nil___ 

reclaim:
  api_key: ___nil___ 

reminders:
  list_mapping: ___nil___

task_bridge_web:
  api_key: ___nil___
